const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.jumpthru,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Audio,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.Scroll,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Cnds.CompareOrientation,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Mouse.Cnds.OnAnyClick,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.PlatformInfo.Acts.RequestWakeLock,
		C3.Plugins.Touch.Acts.RequestPermission,
		C3.Plugins.Touch.Cnds.OnPermissionGranted,
		C3.Plugins.Touch.Cnds.OnPermissionDenied
	];
};
self.C3_JsPropNameTable = [
	{Platform: 0},
	{Player: 0},
	{Jumpthru: 0},
	{Touch: 0},
	{Keyboard: 0},
	{Text: 0},
	{StartText: 0},
	{StartButton: 0},
	{Mouse: 0},
	{PlatformInfo: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Score: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Áudio: 0},
	{esquerda: 0},
	{direita: 0},
	{MinScroll: 0},
	{NextPlatform: 0},
	{score: 0}
];

self.InstanceType = {
	Player: class extends self.ISpriteInstance {},
	Platform: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Text: class extends self.ITextInstance {},
	StartText: class extends self.ITextInstance {},
	StartButton: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Score: class extends self.ITextInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	esquerda: class extends self.ISpriteInstance {},
	direita: class extends self.ISpriteInstance {}
}